# Generated by Django 3.1.4 on 2023-09-28 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('publicplace', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=255)),
                ('schedule', models.DateField()),
            ],
        ),
    ]
